############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
  name  = "Services"
  weight = 3
  identifier = "services"

  # [[main]]
  #   parent = "services"
  #   name   = "Pressure Washing"
  #   url    = "/english/service/pressure-washing/pressure-washing/"
  #   weight = 1

  # [[main]]
  #   parent = "services"
  #   name   = "Fire & Safety"
  #   url    = "/english/service/fire-safety/fire-safety/"
  #   weight = 2

  [[main]]
    parent = "services"
    name   = "Private Cloud & MicroCloud"
    url    = "service/infrastructure/private-cloud/"
    weight = 1

  [[main]]
    parent = "services"
    name   = "Open-Source Applications"
    url    = "service/infrastructure/open-source-apps/"
    weight = 2

  [[main]]
    parent = "services"
    name   = "Managed Infrastructure"
    url    = "service/infrastructure/managed-infrastructure/"
    weight = 3


#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 4

#[[main]]
#name = "Team"
#url = "team/"
#weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 4

#[[main]]
#hasChildren = true
#name = "Pages"
#weight = 8

#[[main]]
#name = "Project"
#parent = "Pages"
#url = "project/"

#[[main]]
#name = "Pricing"
#parent = "Pages"
#url = "pricing/"

#[[main]]
#name = "Elements"
#parent = "Pages"
#url = "elements/"

# footer menu
#[[footer]]
#name = "Legal"
#url = "#"
#weight = 1

#[[footer]]
#name = "Sitemap"
#url = "#"
#weight = 

[[footer]]
name = "Privacy Policy"
url = "#"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "#"
weight = 4
