steps:
  - name: build
    image: hugomods/hugo:exts-non-root
    commands:
      - npm install
      - hugo --minify
    when:
      - event: [push, manual]
        branch: main

  - name: deploy
    image: alpine
    commands:
      - cp -r public/* /deploy/
    volumes:
      - /home/hrparodi/hugo-site:/deploy
    when:
      - event: [push, manual]
        branch: main
